### ISSUE TITLE
Using/ reformatting your pre-compiled database

### ISSUE THREAD

**Issue by naurasd** [wpearman1996/MARES_database_pipeline#2]
Hey guys,

first of all, thanks for the great work setting up and - most importantly - documenting this pipeline. 

I am a newby in the field of bioinformatics and trying to create my first COI customized database. Am teaching myself as much as I can from forums and documentations like yours.

So, my current goal is to generate a COI training fasta for taxonomy assignment. I am working on a DNA metabarcoding project where we target marine eukaryotes. Read denoising and ASV inference is done in dada2, where I also want to perform the taxonomy assignment. I was planning on using the database you have already compiled, not because I am too lazy to generate one on my own, but because we are trying to assess regional diversity plus the occurrence of non-indigenous species. So we do need a very broad database and yours seems perfect for this. I will most likely create a separate one just for the invasive species we already know are common by now in our waters. 

So I have downloaded the tar.gz file of your pre-compiled database (NOBAR in this case). I basically want to transform your fasta to be able to use it in dada2. I have to admit I feel a bit lost, but that's ok, things always work out eventually ;-) What I don't get is what I would need the names.dmp, nodes.dmp and the cust_accession2taxid files for? You have used them in the workflow leading up to the creation of the MARES_NOBAR_BOLD_NCBI_sl_reformatted.fasta, but as this file is provided now, what would I need the three files for? Are they meant for rerunning the scripts of step 4 to reformat the fasta provided by you according to my needs? 

What I also don't understand is what role the nucl_gb.accession2taxid & nucl_wgs.accession2taxid files play in your workflow and what exactly I would need them for? I have gone through every single one of your scripts and these files did not appear there. So what exactly are they supposed to be used for? How did you incorporate them in generating your database?

Would very much appreciate a nudge in the right direction here.

All the best
Nauras

**Comment by wpearman1996** [comment]
Hi Nauras,
Thanks for getting in touch! Hopefully MARES will suit your requirements.
1) The accession2taxids are used by Kraken and Blast to generate the appropriately formatted databases. I don't recall them being required for generating the fasta files throughout the process, only required later on when converting the databases into the blast or kraken formats. Thus we provide three files, the customized nodes, names, and accession2taxid files in order to use in formatting blast and kraken databases.
2) The nucl_gb and nucl_wgs accession2taxids are only required (I think, its been a while since I wrote the code) to construct kraken (and in some cases,  blast) databases from the fasta. The kraken formatted fasta only contains the taxid in the sequence header, so Kraken uses these files to map from taxid back to species ID. 

I havent used dada2 much, but depending on the format you want the database, you should be able to construct this simply with just the fasta file. If you need the taxonomic information in the header, then that may be a bit harder to parse, but should be possible using the nodes & names files and a bit of data wrangling. 
I hope this helps! Let me know if I still haven't answered your question or if i've skipped something important and i'll be happy to help out :) 
Thanks!
William

**Comment by naurasd** [comment]
Hi William,

thanks for getting back to me so quickly and thanks for the clarifications.

I basically need my fasta to look something like this, with levels being Kingdom, Phylum, etc.:

`>Level1;Level2;Level3;Level4;Level5;Level6;
ACCTAGAAAGTCGTAGATCGAAGTTGAAGCATCGCCCGATGATCGTCTGAAGCTGTAGCATGAGTCGATTTTCACATTCAGGGATACCATAGGATAC
>Level1;Level2;Level3;Level4;Level5;
CGCTAGAAAGTCGTAGAAGGCTCGGAGGTTTGAAGCATCGCCCGATGGGATCTCGTTGCTGTAGCATGAGTACGGACATTCAGGGATCATAGGATAC`

So I guess I have to find some way to map the taxonomy information from the nodes and names files to the corresponding accession numbers in the headers of your MARES_NOBAR_BOLD_NCBI_sl_reformatted.fasta.

I'll close this for now, as this will be a more general parsing from here on ;-)

Cheers
Nauras

**Comment by wpearman1996** [comment]
My advice to achieve that format, whilst not probably the most efficient, seems straightforward enough.
Use the following tool to convert the **custom** nodes and names files into a lineage csv.  https://github.com/zyxue/ncbitax2lin

Then, extract the sequence names from the fasta (I do this on line 5 of step5b_prepare_to_MEGAN.sh )
Extract the taxid from those (I would do it R because i'm lazy), then look up (again in R) the taxid in the lineage csv - and extract the relevant rows.
Then you can just paste the columns together with a ";" delimiter, and export a new file to be the new names of the fasta - and then just rename the sequences (I do something similar on line 7 step5_make_krakendb.sh).
Let me know if that helps or if you're struggling and I can try have a go! Feel free to reopen :)

**Comment by wpearman1996** [comment]
Also, note that I haven't spent much time working with dada2, BUT you may encounter issues with multiple sequences of the same name - as some taxids are represented multiple times in our database, so the lineages will be the same. This is because we represent unique haplotypes not taxa in the database. So to overcome this, if it presents an issue, you may want to provide every sequence a unique taxid, which should be possible with some adjusting of our scripts (this sounds like a pain, but it should still work)

**Comment by naurasd** [comment]
> Use the following tool to convert the **custom** nodes and names files into a lineage csv. https://github.com/zyxue/ncbitax2lin

With costum nodes and names, you do mean the ones that come with your tar.gz file, right?

Thanks for the great advice. will try it out and get back to you.

**Comment by wpearman1996** [comment]
Yes, if we provide one (i think we do). Otherwise let me know and i can
give you a copy of the custom one

**Comment by naurasd** [comment]
Hey William, me again. I reopened the issue, fyi.

So I am following your suggestions. Had some issues with ncbitax2lin, but the guys provided me with a lineage.csv.gz, so all good. 

Here is the thing: I extracted the sequence names from the MARES_NOBAR-BOLD_NCBI_sl_reformatted.fasta. So far so good. Loading this txt file into R, this is how the head of this table looks like. 

```
            V1           V2               V3      V4     V5
1  OPPFQ122N17 Lepidocyrtus        paradoxus   49179 COIN5P
2 OPPCE1016N17   Entomobrya          nivalis 1387109 COIN5P
3 PHAPR1159N11   Entomobrya          nivalis 1387109 COIN5P
4  MAMOS035N12        Culex quinquefasciatus    7176 COIN5P
5 OPPCA1198N17   Limnophyes       asquamatus  611509 COIN5P
6  CNTMC658N14      Smittia           315559  COIN5P       
```
So the problem is that where parts of the name are missing, the next column entries just gets placed in there, as seen in row 6. It's a bit of a pain the a#* to sort this out and to extract the taxIDs this way, so I remembered that you also provided the custom cust_accession2taxid file. I thought that this file includes all the accession numbers of the 1,490,251 sequences in your NOBAR database mapped to their corresponding taxIDs, so I can just use this one to extract the taxIDs. However, the cust_accession2taxid consists of 21,457 accession numbers only. I don't really get that, what exactly is that cust_accession2taxid file? Shouldn't it have 1,490,251 rows, one for every accession number in your customized database fasta? What am I overlooking here?

Cheers
Nauras

**Comment by wpearman1996** [comment]
Hi Nauras, 
The table looks corrected, the reason some parts of the name are missing is because sometimes only the genus name is provided in BOLD or GenBank - so we can't assign a species. This isn't actually a problem, but if you want to extract taxids, you could run a simple ifelse statement where if V4 is numeric, then take it, and if it isn't then take V3. Or you could readLines of the file (so its a vector of strings), and then just extract the second to last word. Or you could extract words that are only numeric in composition from the strings. I.e https://stackoverflow.com/questions/18363688/extract-2nd-to-last-word-in-string might help.

Also this file only includes custom taxids, of the 1.4 million sequences, only a small fraction did not have NCBI taxids, so we created a separate file to generate those - so the cust_accession2taxid only includes species for which we had customized ones.
Essentially if you want ALL the taxids, you would need to download a copy of alll the accession2taxid files. Those files are here: https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/ and you need the nucl_gb.accession2taxid & nucl_wgs.accession2taxid.

These files cover ALL species in NCBI, way more than what is in our database - so using this method to get TaxIDs will not give you what you want (well it might eventually, but it would be very inefficient). I would definitely suggest you use some regex to extract the second to last word from the string of sequence names rather than trying to use the accession2taxid files. Also the accession2taxid files are not the in same order as the sequences, so it still wouldn't work for what you're wanting (at least not the way I suggested earlier). 

Thanks,
William

**Comment by wpearman1996** [comment]
Also you need to run the ncbitax2lin script on the modified nodes and names dmp file for this to work - I saw you were having issues with this - so i installed the script and ran it successfully on the modified nodes and names files. I've attached the lineage files below for both MARES_BAR and MARES_NOBAR - so you should only need to fix the issue with the keyword
https://drive.google.com/file/d/1g_gR_rCKsy-_ArRp9cIkdvrcqXRrT_9f/view?usp=sharing

https://drive.google.com/file/d/1D68IXOyAfDr7k6Z4tJ80P8Fpkjt2HNDo/view?usp=sharing

s.

**Comment by naurasd** [comment]
Hi William,

thanks so much for the files and for taking the time to assist me with this. I really appreciate it. Will follow your suggestions and get back to you.

Enjoy the weekend
Nauars

**Comment by naurasd** [comment]
Hi William,

so I was finally able to format the database according to my needs. Man, that was some fight , at least with the limited skills I have :-)

There are still a few discrepancies which appeared in the process, though. From your NOBAR database fasta, I extracted 1,490,251 sequence names. However, in your paper (Table 1) it says your NOBAR database consists of 1,491,691 sequences. It also says there that this corresponds to 19,154 species. But there are 78,844 unique taxID entries in the sequence names I have extracted. There were a few prokaryotic taxa in your NOBAR fasta (guess they were downloaded based on the COIN5P search term), but this does not explain the gap. What am I overlooking?

Thanks again for the great help, I really appreciate it.

Nauras

**Comment by wpearman1996** [comment]
Thanks! I'm note hugely worried about the the smaller discrepancies in
numbers, that can happen with different versions of the database - and i
recall constructing a new one and uploading it to the osf. It shouldn't
really make a huge difference, the inclusion of some prokaryotes was, as i
recall, unavoidable with our search terms - but shouldn't be problematic.

The discrepancy in the number of species is from the table in the paper,
there are approximately 20,000 marine species in the database, and a total
of approximately 79,000 species. So those numbers actually sound about
right. We include non marine species in the database, because many marine
species have closely related non marine species.

**Comment by naurasd** [comment]
Alright, thanks so much. Appreciate that you always got back to me so quickly and for giving so much advice. 

Will close this now ;-)
