### ISSUE TITLE
Quality control of reference sequences in MARES database

### ISSUE THREAD

**Issue by naurasd** [wpearman1996/MARES_database_pipeline#3]
Hey guys,

I formatted both the BAR and NO_BAR databases compiled and provided by you for use with dada2's taxonomy assignment function. dada2 uses the RDP classifier for sequence classification. 

Results weren't of any use, unfortunately. My inferred sequence variants weren't the issue, as I tested classification using MIDORI2 (based on GenBank release 240) and the BOLD identification engine and things looked much better there.

So I checked the sequences in your databases and there is a huge amount of ambiguous bases in the sequences mined for MARES. Is there any quality control you guys have performed before you tested MARES (doesn't say anything about it in your paper or on the Github page)? Given the way the two databases look as provided by you (a lot of N's), I am having a hard time to understand how you were able to meaningfully compare them to other databases, as described in your paper.

Cheers

Nauras

**Comment by wpearman1996** [comment]
Hi there,
Can you please send me some examples excerpts of the ambiguous bases? I.e.
Sequences with lots of them.
I'd expect some ambiguous bases, but not a huuuge amount.
Because we compare based on taxonomic composition based on sequence
metadata rather than specific sequences, if a sequence in the database
contains large amounts od ambiguous bases - then that won't affect our
results in terms of comparing to other databases.

This is probably more an issue with algae and plants which may have larger
mitochondrial genomes, and thus more ambiguity in the genomes in the
database.
Bear in mind, we don't curate the sequences too much - so if the source has
ambiguity, so will our database.
However, it may be an issue with the scripts - I'll try get onto looking
into this later this week once I've got the ambiguous base examples from
you.
Can you also compare the dada2 database for mares to our provided blast or
kraken one? See if it has the same degree of ambiguous bases?

I can always add an extra step to the pipeline to remove sequences that are
>20% N or something similar.
Cheers,
William

**Comment by wpearman1996** [comment]
Hi Nauras,
Thanks for alerting me to this issue! I've looked into it a bit more, and seems like there's probably a bug in the code. I'm going to write up a fix which will remove ambiguous bases at the start and end of sequences - but not in the middle (as that will screw up alignments). It's not the best option for a fix, but in the short term it should work till I get a chance to re-run the entire pipeline to work out what's wrong with it. 
From what I can see so far, it seems like the pipeline is adding extra N's till it reaches a pre-determined length (or something like that) - and so removing the N's after database construction shouldn't be an issue as the actual sequences themselves are remain correct.
I'll try get a temporary fix uploaded in the next couple of days, but i'm pretty busy right now so if it's not done by the end of the week and you're wanting it, just comment on this to remind me. 
Cheers,
William

**Comment by wpearman1996** [comment]
Hi again,
Just an update - it seems like this is primarily an issue for BOLD originating sequences, as bold uses "-" to denote ambiguous bases. So i've added a patch to step4e which removes trailing and leading N's. This should hopefully correct the issue mostly, I will hopefully add a line that will remove sequences if that are > 30% N or something similar shortly.

**Comment by wpearman1996** [comment]
Hi Nauras,
Thanks again for identifying this bug - it seems pretty important! 

I think i've corrected the issue now. All trailing and leading N's are removed, and then sequences with >30% N are removed. You can adjust this percentage easily on line 10 of step4e_Ncorrection.sh

This script can take a while to run because it has to make a table of base composition for every sequence. 
It should run easily (with some minor modifications to names) on your dada formatted fasta, as it doesn't rely on sequences names. The only thing is that it relies on single line fastas - but its pretty easy to convert between singline and multiline. 

Let me know if it works :) 
Cheers,
William

**Comment by naurasd** [comment]
Hi William,

thanks for following up on this so quickly. I am glad you figured out the potential problem in your pipeline. I guess the pipeline adding N's till it reaches the pre-determined to me sounds like an explanation for what is going on. How come BOLD is a source of sequences with many N's? You mean in terms of sequences stored there are shorter and the pipeline adds the N's?

Let me know once you have eliminated the bug. It would be very nice if you could upload the BAR and NO BAR fastas provided by you again once this is done. I was actually using them and not running the entire pipeline, as I usually have a lot of issues installing all dependencies.

Cheers
Nauras

**Comment by naurasd** [comment]
Ah oops, seems like you just commented a few secs ago. Can I just run the N correction on your BAR / NOBAR fastas provided by you?

**Comment by naurasd** [comment]
Alright, thanks William. I will try and run it on my formatted fasta.

Cheers
Nauras

**Comment by wpearman1996** [comment]
Hi Nauras,
BOLD uses "-" to denote an ambiguous base rather than "N". To make it compatible with genbank, we have to replace them with N. 
I'm not sure why BOLD has so many more ambiguities - I expect something like a 2 step PCR, where the internal amplicon is sequence and not the external one is sequenced and so bases are added to denote the first round of primers. Or sanger sequence chromatograms which have messed up beginning and ending sequences get converted to Ns. Honestly i'm not too sure. 

There's probably also some issue with leading and trailing white spaces which means a simple find and replace in the pipeline adds additional N's. I'll try hunt it down when i have the time. 
I'll try to upload new fixed BAR/NBOBAR fastas when I can. 
Feel free to send me your formatted fasta if the new scripts dont work on it - and i'll have a go.
Cheers,

**Comment by naurasd** [comment]
Thanks again, will try and run the N correction. Will let you know if that works ;-)

Thanks for taking the time to figure this out.

Nauras

**Comment by naurasd** [comment]
I am not able to install seqtk which is needed for the N correction script. Asked the seqtk guys but am not sure how regularly they check their Github issue page. will see.

**Comment by wpearman1996** [comment]
Maybe try a conda install? Or just send me your fasta?

Just an update - i've updated (well shortly i will) the code to be much more efficient in calculating N percent (Thanks to biostars!), the pipeline now includes another script for pulling out that info - it's a bioperl based one, so you may find some issues with the pipeline since it requires dependencies. But i'm happy to run it for you, and hopefully update the BAR and NOBAR fastas before too long.

**Comment by naurasd** [comment]
Thanks for the help. Here is the link to my formatted BAR fasta. 

[https://www.dropbox.com/s/pf6cmo9sbbi6sjr/MARES_BAR_BOLD_NCBI_sl_dada2.fasta?dl=0](url)

I can also just wait till you guys upload the new versions of your databases if that's less hassle for you.

**Comment by wpearman1996** [comment]
Here's a corrected version of BAR. Bear in mind, this is all bleeding edge development, so there may still be various issues. I removed sequences with >30% N. You may want this threshold lower.
https://www.dropbox.com/s/mfbfmaqie4u6s82/newbar_Ncorrected.tar.gz?dl=0

**Comment by wpearman1996** [comment]
Also here's the dada2 formatted one 
https://www.dropbox.com/s/e126q3khat8e0ki/dada2_bar.tar.gz?dl=0

**Comment by naurasd** [comment]
cheers, already formatted the other one. it's running now ;-)

**Comment by wpearman1996** [comment]
Hi Nauras,
I'm glad you're using the other one! I realized after trying to format the dada2 one, it won't work because some sequences have the same name - so i can't exclude sequences based on name - which is how i removed the ones which have >30% N.

After looking again at the files, i think even 30% N is too high, and it might be better to drop it to 10%. 
Cheers,

**Comment by naurasd** [comment]
if you send me another fasta with <10% I can run it as well

**Comment by wpearman1996** [comment]
Thanks, i've attached a link. I think it removed ~12,000 sequences.
https://www.dropbox.com/s/4kowufau0deope4/mares_10perc_N.tar.gz?dl=0

**Comment by naurasd** [comment]
Attached are the taxonomy assignment results and corresponding bootstrap values for my 8000+ ASVs. Classification was performed in dada2 which uses the RDP classifier, with a minimum bootstrap value of 50 for assignments. Results look really bad still and at phylum level almost everything gets classified as Arthropoda. As I said, my ASVs are not the problem, I have tested both BOLD only, MIDORI2 and a customized BOLD/GenBank database and results were much better.

For now, I will stop trying to use MARES. Things seem to be working for you using MEGAN or Kraken and as you said, MARES is still new and will be further developed in the near future. I really like your approach and think that this database will be of great use eventually, but it doesn't seem to be working with the pipeline I am using at the moment.

Thanks again for having a detailed look at this.

Cheers
Nauras

[tax_table_mares10N.txt](https://github.com/wpearman1996/MARES_database_pipeline/files/5873953/tax_table_mares10N.txt)
